global using Marketing.Domain;
global using ECommerce.Core.Application;
global using ECommerce.Core.Persistence;
global using Marketing.Application.Dtos;
global using Marketing.Application.Validators;
global using FluentValidation;
global using MediatR;
global using Marten;
global using ECommerce.Core.CQRS;
