services:
  productcatalogdb:
    container_name: productcatalogdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=EcommerceProductCatalog
    volumes:
      - postgres_product_catalog:/var/lib/postgresql/data
